### ISSUE TITLE
[5pt] anticipate packaging via pip

### ISSUE THREAD

**Issue by scasplte2** [Topl/Brambl-Py#15]
- [x] include requirements file
- [x] src folder (or however python does it)

What is the standards for pip?
Are tests suites common?

**Comment by ArjunMehta01** [comment]
@scasplte2 
**Packaging via pip requires the package to contain the following files and folders:**
Setup.py
Test folder contains unit tests(test suites)
__init__.py required to import directory as a package(inside the package and like index.js)
LICENSE

It should also contain the requirements.txt file along with the code in an src folder.

From there Setuptools and wheel need to be installed to compile the package. There are executable commands that go along with wheel when all work has been completed. Finally upload to the python package index

I created a barebones Setup.py file with the setup method without specifics

A step by step process can be found here: 
https://dzone.com/articles/executable-package-pip-install

The official tutorial can be found here:
https://packaging.python.org/tutorials/packaging-projects/
