### ISSUE TITLE
[3pt] Find Python package for crypto

### ISSUE THREAD

**Issue by scasplte2** [Topl/Brambl-Py#19]
- [x] Blake2b-256
- [x] Keccak256
- [x] aes-256-ctr
- [x] scrppt key derivation function
- [x] curve25519
- [x] base58 encoding/decoding

**Comment by ArjunMehta01** [comment]
@scasplte2 
**The documentation and pip installation instructions for each package can be found below:**

**Pyblake2**
https://pypi.org/project/pyblake2/

**Keccak3**
https://pypi.org/project/eth-hash/

**aes-256-ctr(pycrypto)**
https://pypi.org/project/pycrypto/
https://stackoverflow.com/questions/12691168/how-aes-in-ctr-works-for-python-with-pycrypto

**Scrypt key derivation function**
https://pycryptodome.readthedocs.io/en/latest/src/protocol/kdf.html
Pip install pycryptodome

**Curve25519**
https://pypi.org/project/curve25519-donna/

**base 58**
https://pypi.org/project/base58/

**Comment by scasplte2** [comment]
@ArjunMehta01 
So it appears that PyCryptodome https://pycryptodome.readthedocs.io/en/latest/src/introduction.html can cover blake2b, Keccak3, AES-256, and Scrypt (check the API section). I just want to minimize the number of packages we need to bring in. With those covered, we only need two additional packages for Curve25519 and base 58. This looks good 👍

**Comment by scasplte2** [comment]
Actually, this does a better job of summarizing what is available https://pycryptodome.readthedocs.io/en/latest/src/features.html
