### ISSUE TITLE
[2pt] Demo key export from BramblPy and import into BramblJS

### ISSUE THREAD

**Issue by scasplte2** [Topl/Brambl-Py#28]
* Geneate and export a key from BramblPy
* Import that key-pair into BramblJS
* Using the imported key in BramblJS, sign a message.
* Verify that message and signature with BramblPy.

**Comment by ArjunMehta01** [comment]
@scasplte2 

When I was testing the importing of the keys, an error would occur in verifying the MAC. I did some testing and found that the MAC function is not the issue but rather the scrypt keys with identical parameters generated in brambl-Py and brambl-JS are slightly different.
