### ISSUE TITLE
[5pt] investigate web3.py strutcutre

### ISSUE THREAD

**Issue by scasplte2** [Topl/Brambl-Py#7]
- How i it organized?
- What modules / capabilities are included in web3.py?

**Comment by ArjunMehta01** [comment]
I looked through the documentation and source code for Web3.py and found that it is organized similarly to brambl-py. Brambl naming is consistent with the convention. However, each folder contains significantly more files and these python files contain fewer functions. The documentation provided is less in the form of comments. They have a doc folder containing comprehensive documentation with examples. 


Web3.py’s has several capabilities that may be of interest such as:

Local node setup included 
Comprehensive block finder(more functionality than brambl-py)
Data type conversion functions
Address checks 


In terms of full modules, many are directly related to the currency aspects such as mining and gas prices. However, some modules may be of interest including the filter module which would work as a pass through for values passed to brambl-py. Likewise, the brambl request module could utilize several functions from the transaction, utils, and request modules in web3py.
