### ISSUE TITLE
[1pt] Look into asynchronous capabilities of Python

### ISSUE THREAD

**Issue by scasplte2** [Topl/Brambl-Py#8]
is there aysnc/await or callback strings in python?

**Comment by ArjunMehta01** [comment]
The asyncio library can be used for asynchronous programming.

Python can be made to wait and callback does exist.

**Comment by scasplte2** [comment]
@arjunmehta01 cool, could you provide links or material that you found
useful so that I could read up on this a little?

**Comment by ArjunMehta01** [comment]
@scasplte2 
https://hackernoon.com/a-simple-introduction-to-pythons-asyncio-595d9c9ecf8c is a good summary of async IO and its features. The official documentation can be found here https://docs.python.org/3/library/asyncio.html

**Comment by scasplte2** [comment]
Read through the docs, looks very promising. Thanks for sharing ✔️
