### ISSUE TITLE
[1pt] Look into python equivalent to jsdoc

### ISSUE THREAD

**Issue by scasplte2** [Topl/Brambl-Py#9]
would like a tool to autogenerate documentation from ource code

**Comment by ArjunMehta01** [comment]
There are several tools to generate documentation for source code. These include:
- docstrings => for use in python
- Doxygen API => automatic and can create documentation in HTML +others
- pdoc API => command line tool to create documentation for Python Modules

More information is available at: https://wiki.python.org/moin/DocumentationTools

**Comment by scasplte2** [comment]
@arjunmehta01 do you know if any of these integrate with github pages?

I briefly googled some things that might be worth looking into.
Sphinx on github pages -
https://daler.github.io/sphinxdoc-test/includeme.html
Autmating sphinx deployment with actions -
https://github.com/ammaraskar/sphinx-action &
https://github.com/marketplace/actions/deploy-to-github-pages-python

To be clear, I'm not saying to go forward with the action and the pages
right now, we just need to find a documentation tool that will let us
achieve the final product. That final product being that we can automate
the building of the documentation whenever we deploy updates to the master
branch of Topl/Brambl-Py and have the automatically built docs hosted on a
webpage. This automation helps to eliminate extra steps for maintainers to
keep the published documentation up to date.

Lastly, github pages is just a github hosting service for static content
and github actions is a tool for automating processes like running tests,
building executables, deploying etc. Think of it like a powerful scripting
engine that we can require our code to go through whenever we deploy it to
a particular branch.

**Comment by scasplte2** [comment]
@ArjunMehta01 I'd like to close this by settling on something we'll use for documentation. I somehow missed your link previously but that is a really good summary and I am kind of partial to Doxygen. Combined with 
https://github.com/marketplace/actions/doxygen-action and https://github.com/peaceiris/actions-gh-pages

I think we could achieve what we want. Is there a particular tool that you were partial to?

**Comment by ArjunMehta01** [comment]
@scasplte2 I looked into it further and Doxygen seems like the best bet.
